<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Acheron.Core" Version="1.0.1" />
    <PackageReference Include="Silk.NET.GLFW" Version="2.22.0" />
    <PackageReference Include="Silk.NET.OpenGL" Version="2.22.0" />
    <PackageReference Include="StbImageSharp" Version="2.30.15" />
  </ItemGroup>

  <PropertyGroup>
    <PackageId>Acheron.Engine</PackageId>
    <Version>1.0.5</Version>
    <Author>talonateox</Author>
    <Product>Acheron Game Development Framework</Product>

    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

</Project>
